version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: my_finance_db_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password_here  # 這裡設定你的資料庫密碼
      POSTGRES_DB: MyFinanceDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: