GET https://localhost:7121/api/test/secret
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIwZmJlMTFmNi0yMDY2LTQ1NzMtYWI0OC0zMzI4OTI0NWEwN2YiLCJ1bmlxdWVfbmFtZSI6InRlc3RlcjEiLCJuYmYiOjE3NzYzMjU5MjQsImV4cCI6MTc3NjkzMDcyNCwiaWF0IjoxNzc2MzI1OTI0LCJpc3MiOiJNeUZpbmFuY2VBcGkiLCJhdWQiOiJNeUZpbmFuY2VVc2VycyJ9.koNLNxvRo7Dq5Y254-FXJ7Hw8a0WDuo0OVTRBrEpK2k

