DELETE https://localhost:7121/api/transaction/75398d59-6d19-4acc-b3f2-0742cc878e69
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIyNzU2ODcyYy00ZGEyLTQzODMtYWZlZS0xNzk2ODNmN2I3ODAiLCJ1bmlxdWVfbmFtZSI6IkppbW15IiwibmJmIjoxNzc3NjMzMzc5LCJleHAiOjE3NzgyMzgxNzksImlhdCI6MTc3NzYzMzM3OSwiaXNzIjoiTXlGaW5hbmNlQXBpIiwiYXVkIjoiTXlGaW5hbmNlVXNlcnMifQ.jCnFfnRj34DzA4f41Xdh8cg1zHrVuRBsyaY3dPKPciI