PUT https://localhost:7121/api/transaction/f57d47a4-2701-450e-8f05-696f6dff5745
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiI0NjRiNTMzOS03NzJkLTQzMmMtYmEyZi1iNzQ2YjEyZWQ3MWQiLCJ1bmlxdWVfbmFtZSI6IkppbW15IiwibmJmIjoxNzc3NDc1MTY0LCJleHAiOjE3NzgwNzk5NjQsImlhdCI6MTc3NzQ3NTE2NCwiaXNzIjoiTXlGaW5hbmNlQXBpIiwiYXVkIjoiTXlGaW5hbmNlVXNlcnMifQ.wIkZ0e5VJNNFRsBtZ4LtPHWav86XBPIqKYKE6Mr3Bto

{
  "amount": 25,
  "category": "abc",
  "description": "abc",
  "date": "2026-04-16T12:00:00Z"
}