GET https://localhost:7121/api/transaction
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJlZjRlNDM1MC1lYjc1LTQzYmItYWUxNi05YTU1ZWIzMjE2ZmUiLCJ1bmlxdWVfbmFtZSI6InRlc3RlcjIiLCJuYmYiOjE3NzYzNDk3NDIsImV4cCI6MTc3Njk1NDU0MiwiaWF0IjoxNzc2MzQ5NzQyLCJpc3MiOiJNeUZpbmFuY2VBcGkiLCJhdWQiOiJNeUZpbmFuY2VVc2VycyJ9.K9RgHc0yTaCUswFb36UmkQAhEJP1trKq68aEhdII5t0