DELETE https://localhost:7121/api/transaction/57778f22-a92f-4adf-93eb-61a92c9c98b6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiI0NjRiNTMzOS03NzJkLTQzMmMtYmEyZi1iNzQ2YjEyZWQ3MWQiLCJ1bmlxdWVfbmFtZSI6IkppbW15IiwibmJmIjoxNzc4Njg1MDUyLCJleHAiOjE3NzkyODk4NTIsImlhdCI6MTc3ODY4NTA1MiwiaXNzIjoiTXlGaW5hbmNlQXBpIiwiYXVkIjoiTXlGaW5hbmNlVXNlcnMifQ.lU4U66B6wfxIi0LM2RTHnkXhOxaax4FO6uyjyx0Jvpo